name: pull-request
on:
  pull_request:
    branches:
      - master
  workflow_dispatch: {}

jobs:
  npm-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm i
      - run: npm run lint
      - run: npm run zip
